### PR TITLE
Drop Node <6 and bump request version

### PR DESCRIPTION
**Pull request by strugee**
This squashes a whooooole lot of deprecation and security warnings. Test suite passes OK.

### CODE REVIEW

**Comment by strugee** [comment]
Note that I didn't check the changelog too thoroughly, and IIRC request is known to not always respect semver like it should... I'll do it if I find the time but I figured the test suite passing was probably a pretty good indicator.

**Comment by strugee** [comment]
Aaaand sure enough CI failed because request dropped Node 0.10 support in a _minor release_. \*deep sigh\*

I pushed a new version just bumping to the last version to support 0.10. Although really I would recommend just dropping it...

**Comment by strugee** [comment]
So, it turns out that actually tests are failing even without this change because of a transient dep dropping support. So I decided to just bite the bullet and drop support for Node <6. That's what's in this PR now.

**Comment by inikulin** [comment]
Thanks!

**Comment by strugee** [comment]
Sure! Thank _you_!

**Pull request merged**
